# Generated by Django 5.2.18 on 2026-10-10 06:38

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actor', models.CharField(max_length=128)),
                ('table_name', models.CharField(max_length=128)),
                ('row_id', models.BigIntegerField()),
                ('application_id', models.BigIntegerField()),
                ('row_sha256', models.CharField(max_length=64)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.CharField(max_length=320)),
                ('email_key', models.CharField(max_length=320)),
                ('display_name', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('submitted', 'Submitted'), ('contact_verified', 'Contact Verified'), ('evidence', 'Evidence'), ('assessing', 'Assessing'), ('awaiting_answers', 'Awaiting Answers'), ('awaiting_decision', 'Awaiting Decision'), ('on_hold', 'On Hold'), ('admitted', 'Admitted'), ('agreements', 'Agreements'), ('agreements_complete', 'Agreements Complete'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='submitted', max_length=32)),
                ('contact_verified_at', models.DateTimeField(blank=True, null=True)),
                ('next_version_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('stage__in', ('submitted', 'contact_verified', 'evidence', 'assessing', 'awaiting_answers', 'awaiting_decision', 'on_hold', 'admitted', 'agreements', 'agreements_complete', 'provisioning', 'active'))), fields=('email_key',), name='application_one_open_per_email_key'), models.CheckConstraint(condition=models.Q(('stage__in', ('submitted', 'contact_verified', 'evidence', 'assessing', 'awaiting_answers', 'awaiting_decision', 'on_hold', 'admitted', 'agreements', 'agreements_complete', 'provisioning', 'active', 'declined', 'withdrawn', 'closed'))), name='application_stage_valid'), models.CheckConstraint(condition=models.Q(('next_version_number__gte', 1)), name='application_next_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='ContactChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_at_issue', models.CharField(max_length=320)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version_number', models.PositiveIntegerField()),
                ('origin', models.CharField(choices=[('form', 'Form'), ('repeat_after_verification', 'Repeat After Verification')], max_length=32)),
                ('submitted_fields', models.JSONField()),
                ('received_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='VersionAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions', to='applications.application')),
                ('submission_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adoption', to='applications.submissionversion')),
                ('via_challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions', to='applications.contactchallenge')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('applicant', 'Applicant'), ('staff', 'Staff')], max_length=16)),
                ('actor_ref', models.CharField(blank=True, default='', max_length=200)),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('data', models.JSONField(default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='applications.application')),
            ],
            options={
                'indexes': [models.Index(fields=['application', 'occurred_at'], name='event_application_time'), models.Index(condition=models.Q(('kind', 'needs_staff_attention')), fields=['application'], name='event_staff_attention')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ['system', 'applicant', 'staff'])), name='event_actor_type_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='contactchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('superseded_at__isnull', True), ('used_at__isnull', True)), fields=('application',), name='challenge_one_active_per_application'),
        ),
        migrations.AddConstraint(
            model_name='contactchallenge',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='challenge_expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='contactchallenge',
            constraint=models.UniqueConstraint(fields=('id', 'application'), name='challenge_id_application_unique'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.UniqueConstraint(fields=('application', 'version_number'), name='version_number_unique_per_application'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['form', 'repeat_after_verification'])), name='version_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.UniqueConstraint(fields=('id', 'application'), name='version_id_application_unique'),
        ),
        migrations.AddConstraint(
            model_name='versionadoption',
            constraint=models.UniqueConstraint(fields=('application',), name='adoption_one_per_application'),
        ),
        # Hand-added: an adoption's version and challenge must belong to the adoption's own application.
        # Django has no composite foreign key, so these are SQL constraints against the (id, application)
        # unique constraints above. Deferred like Django's own foreign keys.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE applications_versionadoption ADD CONSTRAINT adoption_version_same_application"
                " FOREIGN KEY (submission_version_id, application_id)"
                " REFERENCES applications_submissionversion (id, application_id) DEFERRABLE INITIALLY DEFERRED",
                "ALTER TABLE applications_versionadoption ADD CONSTRAINT adoption_challenge_same_application"
                " FOREIGN KEY (via_challenge_id, application_id)"
                " REFERENCES applications_contactchallenge (id, application_id) DEFERRABLE INITIALLY DEFERRED",
            ],
            reverse_sql=[
                "ALTER TABLE applications_versionadoption DROP CONSTRAINT adoption_challenge_same_application",
                "ALTER TABLE applications_versionadoption DROP CONSTRAINT adoption_version_same_application",
            ],
        ),
    ]
