# Generated by Django 5.2.18 on 2026-10-10 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('template_key', models.CharField(max_length=64)),
                ('template_version', models.CharField(max_length=32)),
                ('recipient', models.CharField(max_length=320)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('rendered', 'Rendered'), ('accepted', 'Accepted'), ('failed', 'Failed')], max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to='applications.application')),
                ('pending_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to='workflow.pendingaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pending_action', 'attempt_number'), name='outbound_unique_per_attempt'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='outbound_attempt_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['rendered', 'accepted', 'failed'])), name='outbound_status_valid')],
            },
        ),
    ]
