# Generated by Django 5.2.18 on 2026-10-10 06:24

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('actor_ref', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id'), name='pause_one_per_subject')],
            },
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('subject_type', models.CharField(max_length=64)),
                ('subject_id', models.UUIDField()),
                ('input_ref', models.CharField(blank=True, default='', max_length=200)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('uncertain', 'Uncertain'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('due_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at'], name='pending_action_status_due')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'running', 'done', 'failed', 'uncertain', 'held', 'cancelled'))), name='pending_action_status_valid'), models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='pending_action_max_attempts_positive'), models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='pending_action_attempts_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'running'), _negated=True), models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False)), _connector='OR'), name='pending_action_running_has_lease')],
            },
        ),
    ]
